baseURL: https://lassembleuse.github.io/les-vigiliantes/
languageCode: fr-fr
title: Les Vigiliantes
theme: bulma-theme
DefaultContentLanguage: fr
metaDataFormat: "yaml"
blackfriday:
  smartypantsQuotesNBSP: true
  extensions:
  - hardLineBreak