baseURL: https://www.vigiliantes.fr 
languageCode: fr-fr
title: Les Vigiliantes
theme: bulma-theme
DefaultContentLanguage: fr
metaDataFormat: "yaml"
blackfriday:
  smartypantsQuotesNBSP: true
  extensions:
  - hardLineBreak
footnoteReturnLinkContents: "↩" 