baseURL: https://www.vigiliantes.fr
languageCode: fr-fr
title: Les Vigiliantes
theme: bulma-theme
DefaultContentLanguage: fr
metaDataFormat: "yaml"
removePathAccents: true
# blackfriday:
#   smartypantsQuotesNBSP: true
#   extensions:
#   - hardLineBreak
# footnoteReturnLinkContents: "↩"
goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    attribute: true
    autoHeadingID: true
    autoHeadingIDType: github
  renderer:
    hardWraps: false
    unsafe: false
    xhtml: false

menu:
  main:
  - identifier: Qui sommes-nous
    name: Qui sommes-nous
    weight: 7
  # - identifier: Ressources
  #   name: Ressources
  #   weight: 100

permalinks:
  actualites: /:year/:month/:title/