baseURL: https://www.vigiliantes.fr
languageCode: fr-fr
title: Les Vigiliantes
theme: bulma-theme
DefaultContentLanguage: fr
metaDataFormat: "yaml"
removePathAccents: true
blackfriday:
  smartypantsQuotesNBSP: true
  extensions:
  - hardLineBreak
footnoteReturnLinkContents: "↩"

menu:
  main:
  - identifier: Qui sommes-nous
    name: Qui sommes-nous
    weight: 1
  - identifier: Ressources
    name: Ressources
    weight: 100

permalinks:
  actualites: /:year/:month/:title/